const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const multer = require('multer')
const upload = multer({dest: 'images/'})
const morgan = require('morgan')
app.use(morgan('dev'))
const cors = require('cors')
app.use(cors())
require('./connection/db')
const router = require('./router')
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))
app.use(express.static(__dirname+'./uploads'))
app.use('/',router)
app.listen(3000, () => {
    console.log(`3000`)
})
